### ISSUE TITLE
Loads normally

### ISSUE THREAD

**Issue by olec04** [shinyquagsire23/SaltySD#14]
texture doesnt load and runs like normal smash
Not Salty

**Comment by phase** [comment]
You're going to need to provide a little more info. What _exactly_ did you do? Did you follow all the instructions?

**Comment by olec04** [comment]
Instructions? All I did was get my saltysd cia and i installed it made the saltysd folder and put my texture mod in it model and ui are the folders that i put in the saltysd folder?!

**Comment by shinyquagsire23** [comment]
Not a help forum
