### ISSUE TITLE
Custom Firmware 

### ISSUE THREAD

**Issue by SolomonAddison** [shinyquagsire23/SaltySD#15]
Does SaltySD require custom firmware? If so, I'm screwed because I'm on the latest firmware. Please someone reply back.

**Comment by Cydget** [comment]
SaltySD does not require a custom firmware, however the only current way to use saltysd is with custom firmware. Your only option is to wait for smea to update hans to work with updates. After that you can load saltysd through hans. Also, this is not an issue, and github is not a help forum.
