### ISSUE TITLE
How do i use hittest.asm?

### ISSUE THREAD

**Issue by Ordim3n** [shinyquagsire23/SaltySD#17]

**Comment by shinyquagsire23** [comment]
```
@ Hitbox display test (1.1.5)
@ Compile this and place it at 0xA2B800
@ Replace entries 0x17, 0x2D, 0x30, 0x32, 0x34 in the animcmd function table with 0xA2B800
```

The patcher does not support this as of now (probably won't for a while unless someone can sort out a circular particle which doesn't have a startup time). You'd compile the .s with -mfpu=vfp, place the binary at vaddr 0xA2B800 and change the entries specified in the animcmd table at 0xC2D1B8 to that address.
