### ISSUE TITLE
It seems like Sun/Moon save files (main) do not load from sd:/saltysd/SunMoon/ .

### ISSUE THREAD

**Issue by ThunderRemix** [shinyquagsire23/SaltySD#19]
I don't know if it is because of the fact that I have a save file already, but it appears that when I put a modified main in sd:/saltysd/SunMoon/, nothing happens and it just loads the normal save. I don't know if it is because I applied this over a modified code.bin (SMPatcher, no lines), but meh. I'm just leaving this here.

**Comment by shinyquagsire23** [comment]
Yeah it works in Citra but perhaps on hardware different things happen. That is a bit concerning though because it might mean that romfs files might also not be redirecting properly.

**Comment by ThunderRemix** [comment]
I made a little edit to the Shop.cro that worked, so it might either be the fact that I applied it over a modified code or perhaps save redirection does work properly on hardware. Meh.

**Comment by ApacheThunder** [comment]
Has the redirect of save been tested with carts? Perhaps the save redirect fails with eShop build but not the cart since eShop does extra things like secure value checking and what not.

**Comment by ApacheThunder** [comment]
I can confirm save redirection fails with cart versions of the game as well. Recently bought a physical copy of Pokémon Moon. Save redirection doesn't seem to work with that one either.
