### ISSUE TITLE
Possible to give Sun and Moon their own unique directories rather than being combined?

### ISSUE THREAD

**Issue by sora10pls** [shinyquagsire23/SaltySD#22]
As someone who's doing 2 different playthroughs at a time (Sun randomizer and Moon ROM hack), it's pretty tedious having to constantly swap the files in the `saltysd/SunMoon/` directory.

I was wondering if it'd be possible for SaltySD to have one unique directory for Sun, and one unique directory for Moon? Literally just `saltysd/Sun/` and `saltysd/Moon/` would work totally fine.

**Comment by shinyquagsire23** [comment]
Certainly doable, would just have to change https://github.com/shinyquagsire23/SaltySD/blob/master/SunMoon/patch.s#L97 to the directory name you'd rather have it at and create two separate bins.

**Comment by sora10pls** [comment]
Thank you so much for that, would have had no idea how to do so otherwise!
