### ISSUE TITLE
Custom menu Music for Smash doesn't work instantly

### ISSUE THREAD

**Issue by AkitoCL** [shinyquagsire23/SaltySD#25]
After the title screen, any of the two original menu themes will play.
The custom music will play when returning to the Character Select screen after a fight or in the vault.
Not sure if this is a Saltysd issue or a game related issue.

**Comment by Ordim3n** [comment]
That's not a SaltySD related issue, rather an issue with your nus3bank,
iirc it's because there's two starting points in the menu theme

**Comment by AkitoCL** [comment]
Weird, I'm running out of ideas.
I've downloaded the menu nus3bank files countless times and it's the same. I even tried different songs.

**Comment by Ordim3n** [comment]
That's not the issue, you need to inject the song into the nus3bank

**Comment by AkitoCL** [comment]
I just tried that now and also didn't work.

Again, the original music plays in the menu but in the vault it plays just fine.
The only difference now is that it doesn't even play after matches now.

**Comment by shinyquagsire23** [comment]
https://github.com/shinyquagsire23/SaltySD/blob/master/smash/sdsound.asm#L6 is all I have for custom music so there's not a whole lot that can go wrong there I don't think. There might just be param files which need editing for music to work 100%.
