### ISSUE TITLE
Gametext from SD redirection overwritten by game patch....

### ISSUE THREAD

**Issue by ApacheThunder** [shinyquagsire23/SaltySD#27]
This issue seems limited to the new 1.1 version of SaltySD and The Pokémon Sun/Moon 1.1 patch.

I've replaced a string for Smeargle (renamed the Pokémon's species name). I noticed it no longer reflects this change with latest commit of SaltySD. Seems the game's 1.1 patch overrides the gametext garc despite having specified one in my saltySD folder for this game. I even updated the gametext garc in the files I use with pk3ds with the one from the game patch and redid my edit. The new garc is still overridden by the game patch. :(

My icon and model swaps still work however. So this issue seems limited to this specific case and rules out an issue with my CFW or the code.bin I used. Aside from that I have not yet noticed any other fails on garc edits. But if I spot more I will mention them.

EDIT: It seems that SaltySD only redirects romfs of the game but not the romfs of the patch. This may explain why it didn't work for the one garc I modified that the patch also uses. You will certainly need to fix this oversight. :P

**Comment by shinyquagsire23** [comment]
Fixed 5d4ea29c927a2e9
