### ISSUE TITLE
Saving game without a main in SaltySD crashes the game...

### ISSUE THREAD

**Issue by ApacheThunder** [shinyquagsire23/SaltySD#28]
Seems save redirection is suddenly working on hardware now.(didn't see your twitter post about this at first so this caught me by surprise)

This resulted in the game crashing when attempting to save the game when no main file is present in SunMoon folder of SaltySD. (this may be a bug)

The result was a 4kb corrupted main file created in SaltySD/SunMoon. This prevented me from resuming my valid save. So I had to export save with SaveDataFiler to recover the save from before I attempted to save. Before I attempted to save, SaltySD had the game use the main file for each game from it's normal location. It's only when I attempted to save that problems resulted.

But after placing valid main file in SaltySD\SunMoon save redirection seems to work properly now. This could cause issues for new users of this plus the inconsistant state created after attempting to save.

Seems SaltySD requires a valid save in SunMoon on SD now if users wish to save while this patch is active. This is sorta a problem as the previous version did not have this working on hardware, so users will certainly not have a main file present on SunMoon folder. 

I suggest having a separate main file each game at the least if you continue to have both games share the same SunMoon folder. Currently SaltySD uses the same main for both Sun and Moon. This....will create problems. I want these games to use separate saves.

Because of this, I have to disable SaltySD entirely for one of the games until this is resolved. Please fix this ASAP.

**Comment by shinyquagsire23** [comment]
Fixed with 2df6cbaf7c2e8 ? Let me know if that actually works because I've only been testing in emulation at the moment.

**Comment by ApacheThunder** [comment]
Reorganizing my PC box in Moon currently. Will test as soon as I finish. :P

**Comment by ApacheThunder** [comment]
Ok it's no longer crashing. Seems save redirection no longer works now. Placed main save from Sun in SunMoon folder and Moon didn't use it. Perhaps you disabled that or it's just broke again on hardware. Suppose I can live with that. Would rather see it working again once you have Sun and Moon using separate folders. :P

Since the crash on write issue was fixed, I'll close this issue. :P

**Comment by DrSalvador555** [comment]
A bit late to the party, but thanks for alerting us. I just had the save issue, and replacing the broken/nonexistent main file in SaltySD fixed the issue. Wouldn't let me save or delete the save or anything before. Saves and loads perfect now! Much thanks!
