### ISSUE TITLE
How to save when using SaltySD with Pokemon Moon?

### ISSUE THREAD

**Issue by LightningRod33** [shinyquagsire23/SaltySD#30]
Whenever I save with SaltySD on with my Pokemon Moon (cartridge), the game crashes, creates a main file in the SunMoon folder which doesn't seem to work, and the saved data is lost. Is there a way to save?

**Comment by edwarbad23** [comment]
Same problem!!! plz help!!!

**Comment by shinyquagsire23** [comment]
2df6cbaf7c2e842e373973861a2333d5920889df explicitly stops data:/ from being redirected, make sure you have the latest build.
