### ISSUE TITLE
Slow Loading Sm4sh 3ds

### ISSUE THREAD

**Issue by AngelSora** [shinyquagsire23/SaltySD#31]
I'm really tired of slow loading on Smash 3ds. But please tell me if you CAN fix that. If you can't well... i gotta deal with that. :/

**Comment by shinyquagsire23** [comment]
I've heard complains about slow loading on EUR, tested it myself, and have not been able to reproduce the issue at all. Make sure you aren't using any sketchy builds included in CIAs and that you have the latest version possible. A good way to tell if you're on a much older version is if you need any sort of cachegen at all, the latest version completely revamped the loading and does it threaded. There should also be minimal pausing with the Smash ball loading circle. If it has significant pauses, you are likely on an older version.

**Comment by AngelSora** [comment]
My Micro sd card is 64gb but i think the speed is lower than yours... so can't it be better ? (Also I'm using the USA Version)

**Comment by Ordim3n** [comment]
which class is your sd card (it's usually a number is a circle)

**Comment by Cydget** [comment]
Has anybody else noticed a fair bit of lag when loading/viewing replays? I feel like it is accessing the sd card, so it tries to load the mods again. It doesn't matter too much, but is it that kind of lag you are talking about, or is it more of slow menus, because I have no lag in any menus. I also have a class 10 64GB SDXC card if that helps.

**Comment by AngelSora** [comment]
it seems that is also a Class 10 Micros SD i have.

**Comment by AngelSora** [comment]
And i forgot to mention another problem, When Smash Run's time is up, it goes to the total stats (Slowly) and then The Final Battle but... It never stop loading with the circle, its stuck here forever ! (Or maybe a VERY Long time because I'm a bit impatient against this)

**Comment by AngelSora** [comment]
Is there any kind of Formatting that can make my MicroSD The Fastest possible ?

**Comment by firegodjr** [comment]
Unfortunately the only real solution besides using the latest version of SaltySD is to get a new SD card, since the 3ds doesn't support ext formatting

**Comment by AngelSora** [comment]
Great News ! I replaced my microSD Card with a 128gb with 80 mb/seconds and it loads a lot more Faster than usual. This issue can be closed. ;)

**Comment by shinyquagsire23** [comment]
Thanks, I'll probably mention SD speeds in the readme.
