### ISSUE TITLE
How can i make it work on eur 3DS ?

### ISSUE THREAD

**Issue by Linkdu69003** [shinyquagsire23/SaltySD#32]
Hi, I modded ssb4 with saltysd, it only works with us version, but online don't work on my eur 3ds ( issue with aggreements service )
Well, is it possible to make a .bin file for eur 3ds ?

Thanks

**Comment by Gnarmagon** [comment]
Dude thats normal ?
Do you want to get banned ?
Nintendo can see that you are using a Mod !!!
