### ISSUE TITLE
SSB4 Does Not Boot With SaltySD Enabled. Need help

### ISSUE THREAD

**Issue by EnderPika132** [shinyquagsire23/SaltySD#39]
Uh, yeah so I use SaltySD to run Super Smash Bros 4 3ds Mods, except now, when i use SaltySD [i also use Luma as my CFW] my game crashes, and gives an error cause of the new Luma version. I don't know why it does this, but can I get help on to fixing it?

**Comment by EnderPika132** [comment]
So it actually started when I updated to Luma 7, but then i could only run model-type mods for fighters, nothing else. Everything else crashed the game. Eventually it progressed into when game patching/SaltySD is enabled, the game crashes. I seriously want help

**Comment by FateForWindows** [comment]
Try compiling SaltySD yourself. That's the way that you're meant to do it.

**Comment by EnderPika132** [comment]
i'm not that experienced >.< i don't know how to compile SaltySD myself... I just want a fix :I

**Comment by FateForWindows** [comment]
Sorry, then. I can't help you since giving you a code.bin due to legal risks. Try to find a different version. Just a warning: don't use IPS versions. They've been confirmed to have issues.
