### ISSUE TITLE
How to load

### ISSUE THREAD

**Issue by cUReS0da** [shinyquagsire23/SaltySD#4]
I've been trying for a while and I can't figure out how to get the SD card to read the files.

**Comment by Cydget** [comment]
After installing a saltysd update cia, make a folder on the root of your sdcard called "saltysd" and inside that a folder called "smash". Now, if you want to replace any file, put it in the same file structure as when it was extracted. So if you wanted to edit captainfalcon's moveset you place game.bin in /saltysd/smash/animcmd/fighter/captain/game.bin

**Comment by shinyquagsire23** [comment]
Seems to have been solved, although the issue tracker isn't a help forum.
