### ISSUE TITLE
Kirby Hat

### ISSUE THREAD

**Issue by Cydget** [shinyquagsire23/SaltySD#5]
So, I noticed last update that kirby didn't get a hat when absorbing characters, and when kirby absorbed bayonetta it crashed the game. This may be an issue with smash 114 not saltysd, so I was wondering if you could recreate this to confirm.

**Comment by shinyquagsire23** [comment]
I've recreated this and can confirm, the real question to ask I suppose is why. I have a feeling it's something with the lib::Resource::load hacks, which seem to have caused a few issues on their own.

**Comment by shinyquagsire23** [comment]
Fixed d99f5aa34818cb82c72f8c579aaca7bb8233a510
